# Generated by Django 3.2.9 on 2021-11-21 21:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=100)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField(null=True)),
                ('item_price', models.FloatField()),
                ('item_measurement_unit', models.CharField(max_length=100)),
                ('item_main_image', models.ImageField(default='images/product/main.jpg', upload_to='images/product')),
                ('item_extra_image1', models.ImageField(default='images/product/extra1.jpg', null=True, upload_to='images/product')),
                ('item_extra_image2', models.ImageField(default='images/product/extra2.jpg', null=True, upload_to='images/product')),
                ('item_extra_image3', models.ImageField(default='images/product/extra3.jpg', null=True, upload_to='images/product')),
                ('item_extra_image4', models.ImageField(default='images/product/extra4.jpg', null=True, upload_to='images/product')),
                ('category', models.CharField(choices=[('metal and steel work', 'Metal and Steel Work'), ('cement', 'Cement'), ('ceramics', 'Ceramics'), ('plastics', 'plastics'), ('wood and timber', 'Wood and Timber'), ('sand and stone', 'Sand and Stone'), ('bricks and masonry', 'Bricks and Masonry'), ('fabricators', 'Fabricators'), ('tools', 'Tools'), ('glass', 'Glass'), ('electrical systems', 'Electrical Systems'), ('paints', 'Paints'), ('plumbing', 'Plumbing'), ('security systems', 'Security Systems'), ('doors and windows', 'Doors and Windows'), ('telecommunications equipment', 'Telecomunications Equipment'), ('building safety', 'Building Safety'), ('furniture', 'Furniture'), ('surface finishing', 'Surface Finishing'), ('protection', 'Protection'), ('roofing', 'Roofing'), ('conveyor systems', 'Conveyor Systems'), ('composites', 'Composites'), ('flooring', 'Flooring'), ('adhesives', 'Adhesives'), ('others', 'Others')], default='others', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_reg_no', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('town', models.CharField(max_length=50)),
                ('local_area_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=100)),
                ('business_reg_doc', models.ImageField(default='images/profile/profile.jpg', upload_to='images/profile')),
                ('profile_pic', models.ImageField(default='images/profile/profile.jpg', upload_to='images/profile')),
                ('registration_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_mode', models.CharField(choices=[('m-pesa', 'M-pesa')], max_length=100)),
                ('amount', models.FloatField()),
                ('transaction_code', models.CharField(max_length=200)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jengabay.buyer')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jengabay.seller')),
            ],
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcounty_name', models.CharField(max_length=100)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jengabay.county')),
            ],
        ),
        migrations.AddField(
            model_name='seller',
            name='sub_county',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jengabay.subcounty'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placed', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('total_amount_payable', models.FloatField()),
                ('is_delivered', models.BooleanField(default=False)),
                ('date_delivered', models.DateTimeField(null=True)),
                ('ordered_items', models.ManyToManyField(to='jengabay.Item')),
                ('payment_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='jengabay.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='item_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jengabay.seller'),
        ),
    ]
