# Generated by Django 5.0.7 on 2024-09-06 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jengabay", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_transaction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jengabay.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="payer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jengabay.buyer",
            ),
        ),
    ]
